[[pages]]
path = "app/pages/main.py"
name = "Ğ“Ğ»Ğ°Ğ²Ğ½Ğ°Ñ"
icon = "ğŸ "

[[pages]]
name = "Ğ¢Ñ€ĞµĞ½Ğ´Ñ‹"
icon = "ğŸ“ˆ"
is_section = true

[[pages]]
path = "app/pages/trends.py"
name = "Ğ“Ñ€Ğ°Ñ„Ğ¸ĞºĞ¸ Ñ‚Ñ€ĞµĞ½Ğ´Ğ¾Ğ²"
icon = "ğŸŸ¡"

[[pages]]
path = "app/pages/combined_trends.py"
name = "ĞšĞ¾Ğ¼Ğ±Ğ¸Ğ½Ğ¸Ñ€Ğ¾Ğ²Ğ°Ğ½Ğ½Ñ‹Ğµ Ñ‚Ñ€ĞµĞ½Ğ´Ñ‹"
icon = "ğŸŸ¡"

[[pages]]
name = "Ğ¨ÑƒĞ¼"
icon = "ğŸ§"
is_section = true

[[pages]]
path = "app/pages/noise.py"
name = "Ğ¡Ğ»ÑƒÑ‡Ğ°Ğ¹Ğ½Ñ‹Ğ¹ ÑˆÑƒĞ¼"
icon = "ğŸ”´"

[[pages]]
path = "app/pages/simple_noise.py"
name = "Ğ¨ÑƒĞ¼ Ñ Ğ¿Ğ¾Ğ¼Ğ¾Ñ‰ÑŒÑ Ğ½ĞµÑĞ»Ğ¾Ğ¶Ğ½Ğ¾Ğ³Ğ¾ Ğ³ĞµĞ½ĞµÑ€Ğ°Ñ‚Ğ¾Ñ€Ğ°"
icon = "ğŸ”´"

[[pages]]
path = "app/pages/emission.py"
name = "Ğ’Ñ‹Ğ±Ñ€Ğ¾Ñ"
icon = "ğŸ”´"

[[pages]]
name = "Ğ“Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ¸ ĞŸĞ¾Ğ»Ğ¸Ğ³Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑÑ‹"
icon = "â˜¯ï¸"
is_section = true

[[pages]]
path = "app/pages/harm_process.py"
name = "Ğ“Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑ"
icon = "ğŸ”µ"

[[pages]]
path = "app/pages/polyharm_process.py"
name = "ĞŸĞ¾Ğ»Ğ¸Ğ³Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑ"
icon = "ğŸ”µ"

[[pages]]
name = "ĞĞ½Ğ°Ğ»Ğ¸Ğ· .dat Ñ„Ğ°Ğ¹Ğ»Ğ°"
icon = "ğŸ—„ï¸"
is_section = true

[[pages]]
path = "app/pages/volume.py"
name = "Ğ§Ñ‚ĞµĞ½Ğ¸Ğµ Ñ„Ğ°Ğ¹Ğ»Ğ°"
icon = "ğŸŸ¢"

[[pages]]
name = "ĞĞ´Ğ´Ğ¸Ñ‚Ğ¸Ğ²Ğ½Ğ°Ñ Ğ¼Ğ¾Ğ´ĞµĞ»ÑŒ"
icon = "ğŸ”„"
is_section = true

[[pages]]
path = "app/pages/additive_model.py"
name = "ĞĞ´Ğ´Ğ¸Ñ‚Ğ¸Ğ²Ğ½Ğ°Ñ Ğ¼Ğ¾Ğ´ĞµĞ»ÑŒ Ñ‚Ñ€ĞµĞ½Ğ´Ğ¾Ğ² Ñ Ğ´Ñ€ÑƒĞ³Ğ¸Ğ¼Ğ¸ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑĞ°Ğ¼Ğ¸"
icon = "ğŸŸ£"

[[pages]]
path = "app/pages/anti_spike.py"
name = "ĞŸĞ¾Ğ´Ğ°Ğ²Ğ»ĞµĞ½Ğ¸Ğµ Ğ²Ñ‹Ğ±Ñ€Ğ¾ÑĞ¾Ğ²"
icon = "ğŸŸ£"

[[pages]]
path = "app/pages/linear_additive_model.py"
name = "Ğ£Ğ´Ğ°Ğ»ĞµĞ½Ğ¸Ğµ Ñ‚Ñ€ĞµĞ½Ğ´Ğ¾Ğ²"
icon = "ğŸŸ£"