[[pages]]
path = "app/pages/main.py"
name = "Ğ“Ğ»Ğ°Ğ²Ğ½Ğ°Ñ"
icon = "ğŸ "

[[pages]]
name = "Ğ¢Ñ€ĞµĞ½Ğ´Ñ‹"
icon = "ğŸ“ˆ"
is_section = true

[[pages]]
path = "app/pages/trends/trends.py"
name = "Ğ’Ğ¸Ğ·ÑƒĞ°Ğ»Ğ¸Ğ·Ğ°Ñ†Ğ¸Ñ Ñ‚Ñ€ĞµĞ½Ğ´Ğ¾Ğ²Ñ‹Ñ… Ğ´Ğ°Ğ½Ğ½Ñ‹Ñ…"
icon = "ğŸŸ¡"

[[pages]]
path = "app/pages/trends/combined_trends.py"
name = "ĞšÑƒÑĞ¾Ñ‡Ğ½Ğ°Ñ Ñ„ÑƒĞ½ĞºÑ†Ğ¸Ñ"
icon = "ğŸŸ¡"

[[pages]]
name = "Ğ¨ÑƒĞ¼"
icon = "ğŸ§"
is_section = true

[[pages]]
path = "app/pages/noises/noise.py"
name = "Ğ¡Ğ»ÑƒÑ‡Ğ°Ğ¹Ğ½Ñ‹Ğ¹ ÑˆÑƒĞ¼"
icon = "ğŸ”´"

[[pages]]
path = "app/pages/noises/anti_noise.py"
name = "ĞŸĞ¾Ğ´Ğ°Ğ²Ğ»ĞµĞ½Ğ¸Ğµ ÑˆÑƒĞ¼Ğ°"
icon = "ğŸ”´"

[[pages]]
path = "app/pages/noises/simple_noise.py"
name = "Ğ¨ÑƒĞ¼ Ñ Ğ¿Ğ¾Ğ¼Ğ¾Ñ‰ÑŒÑ Ğ½ĞµÑĞ»Ğ¾Ğ¶Ğ½Ğ¾Ğ³Ğ¾ Ğ³ĞµĞ½ĞµÑ€Ğ°Ñ‚Ğ¾Ñ€Ğ°"
icon = "ğŸ”´"

[[pages]]
path = "app/pages/noises/emission.py"
name = "Ğ’Ñ‹Ğ±Ñ€Ğ¾Ñ"
icon = "ğŸ”´"

[[pages]]
name = "Ğ“Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ¸ ĞŸĞ¾Ğ»Ğ¸Ğ³Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑÑ‹"
icon = "â˜¯ï¸"
is_section = true

[[pages]]
path = "app/pages/different_processes/harm_process.py"
name = "Ğ“Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑ"
icon = "ğŸ”µ"

[[pages]]
path = "app/pages/different_processes/polyharm_process.py"
name = "ĞŸĞ¾Ğ»Ğ¸Ğ³Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑ"
icon = "ğŸ”µ"

[[pages]]
name = "Ğ Ğ°Ğ±Ğ¾Ñ‚Ğ° Ñ Ñ„Ğ°Ğ¹Ğ»Ğ°Ğ¼Ğ¸"
icon = "ğŸ—„ï¸"
is_section = true

[[pages]]
path = "app/pages/file_analysis/volume.py"
name = "Ğ§Ñ‚ĞµĞ½Ğ¸Ğµ Ñ„Ğ°Ğ¹Ğ»Ğ°"
icon = "ğŸŸ¢"

[[pages]]
path = "app/pages/file_analysis/filter.py"
name = "Ğ¤Ğ¸Ğ»ÑŒÑ‚Ñ€Ğ°Ñ†Ğ¸Ñ"
icon = "ğŸŸ¢"

[[pages]]
path = "app/pages/file_analysis/waw_files.py"
name = "ĞĞ±Ñ€Ğ°Ğ±Ğ¾Ñ‚ĞºĞ° .wav Ñ„Ğ°Ğ¹Ğ»Ğ¾Ğ²"
icon = "ğŸŸ¢"

[[pages]]
name = "ĞĞ´Ğ´Ğ¸Ñ‚Ğ¸Ğ²Ğ½Ğ°Ñ/ĞœÑƒĞ»ÑŒÑ‚Ğ¸Ğ¿Ğ»Ğ¸ĞºĞ°Ñ‚Ğ¸Ğ²Ğ½Ğ°Ñ Ğ¼Ğ¾Ğ´ĞµĞ»ÑŒ"
icon = "ğŸ”„"
is_section = true

[[pages]]
path = "app/pages/additive_models/additive_model.py"
name = "ĞĞ´Ğ´Ğ¸Ñ‚Ğ¸Ğ²Ğ½Ğ°Ñ Ğ¼Ğ¾Ğ´ĞµĞ»ÑŒ Ñ‚Ñ€ĞµĞ½Ğ´Ğ¾Ğ² Ñ Ğ´Ñ€ÑƒĞ³Ğ¸Ğ¼Ğ¸ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑĞ°Ğ¼Ğ¸"
icon = "ğŸŸ£"

[[pages]]
path = "app/pages/additive_models/anti_spike.py"
name = "ĞŸĞ¾Ğ´Ğ°Ğ²Ğ»ĞµĞ½Ğ¸Ğµ Ğ²Ñ‹Ğ±Ñ€Ğ¾ÑĞ¾Ğ²"
icon = "ğŸŸ£"

[[pages]]
path = "app/pages/additive_models/linear_additive_model.py"
name = "Ğ£Ğ´Ğ°Ğ»ĞµĞ½Ğ¸Ğµ Ñ‚Ñ€ĞµĞ½Ğ´Ğ¾Ğ²"
icon = "ğŸŸ£"

[[pages]]
path = "app/pages/additive_models/noise_harm.py"
name = "Ğ£Ğ´Ğ°Ğ»ĞµĞ½Ğ¸Ñ Ñ‚Ñ€ĞµĞ½Ğ´Ğ° Ğ² ÑˆÑƒĞ¼Ğµ Ğ¸ Ğ³Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¾Ğ¼ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑĞµ"
icon = "ğŸŸ£"

[[pages]]
name = "ĞŸÑƒĞ»ÑŒÑ"
icon = "ğŸ’“"
is_section = true

[[pages]]
path = "app/pages/multi_models/cardiogram.py"
name = "ĞšĞ°Ñ€Ğ´Ğ¸Ğ¾Ğ³Ñ€Ğ°Ğ¼Ğ¼Ğ°"
icon = "ğŸŸ "

[[pages]]
path = "app/pages/multi_models/pulse.py"
name = "Ğ˜Ğ¼Ğ¿ÑƒĞ»ÑŒÑĞ½Ğ°Ñ Ñ€ĞµĞ°ĞºÑ†Ğ¸Ñ"
icon = "ğŸŸ "