[[pages]]
path = "app/pages/main.py"
name = "Ğ“Ğ»Ğ°Ğ²Ğ½Ğ°Ñ"
icon = "ğŸ "

[[pages]]
name = "Ğ¡Ğ»ÑƒÑ‡Ğ°Ğ¹Ğ½Ñ‹Ğµ Ğ·Ğ½Ğ°Ñ‡ĞµĞ½Ğ¸Ğµ"
icon = "ğŸ”€"
is_section = true

[[pages]]
path = "app/pages/noise.py"
name = "Ğ¨ÑƒĞ¼"
icon = "ğŸ§"

[[pages]]
path = "app/pages/emission.py"
name = "Ğ’Ñ‹Ğ±Ñ€Ğ¾Ñ"
icon = "â˜¢ï¸"

[[pages]]
path = "app/pages/harm_process.py"
name = "Ğ“Ğ°Ñ€Ğ¼Ğ¾Ğ½Ğ¸Ñ‡ĞµÑĞºĞ¸Ğ¹ Ğ¿Ñ€Ğ¾Ñ†ĞµÑÑ"
icon = "â˜¯ï¸"

[[pages]]
path = "app/pages/volume.py"
name = "Ğ§Ñ‚ĞµĞ½Ğ¸Ğµ Ñ„Ğ°Ğ¹Ğ»Ğ°"
icon = "ğŸ—„ï¸"

[[pages]]
name = "Ğ¢Ñ€ĞµĞ½Ğ´Ñ‹"
icon = "ğŸ“ˆ"
is_section = true

[[pages]]
path = "app/pages/trends.py"
name = "Ğ“Ñ€Ğ°Ñ„Ğ¸ĞºĞ¸ Ñ‚Ñ€ĞµĞ½Ğ´Ğ¾Ğ²"
icon = "ğŸ“Š"

[[pages]]
path = "app/pages/combined_trends.py"
name = "ĞšĞ¾Ğ¼Ğ±Ğ¸Ğ½Ğ¸Ñ€Ğ¾Ğ²Ğ°Ğ½Ğ½Ñ‹Ğµ Ñ‚Ñ€ĞµĞ½Ğ´Ñ‹"
icon = "â­ï¸"
